---
title: "Day 2 comp session - Data types!!"
format: html
editor: visual
execute: 
  warning: false
  message: false
---

```{r}
library(tidyverse)
```

# Making vectors!

### A character vector

```{r}
dogs <- c("teddy", "khora", "waffle", "banjo", "tallie")

class(dogs)
```

```{r}
cats <- c("creamsicle wolf", 14.2, 3L)

class(cats)
```

### A numeric vector

```{r}
years <- c(20, 40, 16, 2)

#Conditional check
#is. <<< asks questions
#as. <<< gives command

is.numeric(years)
is.character(years)
```

```{r}
dog_food <- c(teddy = "purina", khora = "alpo", waffle = "fancy feast")

dog_food

dog_food[2]
```

```{r}
cars <- c("blue", "orange", "white")

i <- seq(1 : 2)

cars[i]

cars[3]  <- "yellow"

cars
```

# Matrices

```{r}
fish_size <- matrix(c(12, 14, 18, 20), ncol = 2, nrow = 2, byrow = FALSE)

fish_size

#Example indexing 

fish_size[1,1]
fish_size[2,1]


#What happens if we create a matrix with different types of data?

fish_type <- matrix(c(12, "trout", 18, 13L), ncol = 2, nrow = 2, byrow = FALSE)

class(fish_type)

fish_size[2,]
fish_size[,1]
```

# Lists

Reminder: a list combines vectors that can be of different length and type

```{r}
urchins <- list("blue", c(1, 2, 3), c("a cat", "a dog"), 5L)
urchins
```

## Make a named list

```{r}

tacos <- list(topping = c("onion", "cilantro", "guacamole"), 
              filling = c("beans", "meat", "veggies"),
              price = c(6.75, 8.25, 9.5))

tacos


#Index list elements by name

tacos$filling

tacos$filling[2]


```

the second value of dogs is `r tacos$filling[2]`

# Dataframes

```{r}

topping = c("onion", "cilantro", "guacamole")

filling = c("beans", "meat", "veggies")

price = c(6.75, 8.25, 9.5)

df_ex_1 <- data.frame(topping, filling, price)

df_ex_1

class(df_ex_1)



df_ex_2 <- data.frame(topping = c("sour cream", "salsa", "cheese"), 
                      filling = c("chicken", "more cheese", "cabbage"),
                      price = c(12.50, 13.75, 15))

class(df_ex_2)

df_ex_3 <-tribble(
  ~topping, ~filling, ~price,
  "avocado", "steak", 13.25,
  "radish", "fish", 10.40,
  "salsa", "veggies", 9.75
)

class(df_ex_3)

df_ex_3$price[3]
```
